package main

import (
	"go/types"
	"log"
	"os"
	"text/template"

	"golang.org/x/tools/go/packages"
)

func main() {
	pkgs, err := packages.Load(&packages.Config{
		Mode: packages.NeedTypes | packages.NeedTypesInfo,
	}, "github.com/fira42073/nullgen/nullgen")
	if err != nil {
		log.Fatal(err)
	}

	var entries []Entry
	imports := map[string]string{}

	scope := pkgs[0].Types.Scope()
	for _, name := range scope.Names() {
		obj := scope.Lookup(name)
		t, ok := obj.Type().Underlying().(*types.Struct)
		if !ok || t.NumFields() != 2 {
			continue
		}

		valueField := t.Field(0)
		nullField := t.Field(1)

		// Find the inner field of the NullType that is not "Valid"
		nullStruct, ok := nullField.Type().Underlying().(*types.Struct)
		if !ok {
			continue
		}

		var inner string
		for i := 0; i < nullStruct.NumFields(); i++ {
			f := nullStruct.Field(i)
			if f.Name() != "Valid" {
				inner = f.Name()
				break
			}
		}
		if inner == "" {
			continue
		}

		// Qualifier for TypeString
		qual := func(p *types.Package) string {
			if p == nil {
				return ""
			}
			// Record import for package
			imports[p.Path()] = p.Name()
			return p.Name()
		}

		entries = append(entries, Entry{
			Name:      obj.Name(),
			ValueType: types.TypeString(valueField.Type(), qual),
			NullType:  types.TypeString(nullField.Type(), qual),
			NullField: inner,
		})
	}

	// Open output file
	f, err := os.OpenFile("nullgen/nullable.gen.go", os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0o666)
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()

	// Execute template
	data := struct {
		Entries []Entry
		Imports map[string]string
	}{
		Entries: entries,
		Imports: imports,
	}

	tpl := template.Must(template.New("gen").Parse(codeTemplate))
	if err := tpl.Execute(f, data); err != nil {
		log.Fatal(err)
	}
}

type Entry struct {
	Name      string
	ValueType string
	NullType  string
	NullField string
}

const codeTemplate = `// Code generated by nullable. DO NOT EDIT.
package nullgen

import (
{{- range $path, $name := .Imports }}
    {{ $name }} "{{ $path }}"
{{- end }}
)

{{ range .Entries }}
/* -------------------- {{.Name}} -------------------- */

func {{ .Name }}ToNull(v {{ .ValueType }}) {{ .NullType }} {
	return {{ .NullType }}{ {{ .NullField }}: v, Valid: true }
}

func {{ .Name }}PtrToNull(v *{{ .ValueType }}) {{ .NullType }} {
	if v == nil {
		return {{ .NullType }}{}
	}
	return {{ .NullType }}{ {{ .NullField }}: *v, Valid: true }
}

func NullTo{{ .Name }}(n {{ .NullType }}) {{ .ValueType }} {
	return n.{{ .NullField }}
}

func NullTo{{ .Name }}Ptr(n {{ .NullType }}) *{{ .ValueType }} {
	if !n.Valid {
		return nil
	}
	return &n.{{ .NullField }}
}
{{ end }}
`
