// Code generated by nullable. DO NOT EDIT.
package nullgen

import (
    sql "database/sql"
    uuid "github.com/google/uuid"
    time "time"
)


/* -------------------- BoolType -------------------- */

func BoolTypeToNull(v bool) sql.NullBool {
	return sql.NullBool{ Bool: v, Valid: true }
}

func BoolTypePtrToNull(v *bool) sql.NullBool {
	if v == nil {
		return sql.NullBool{}
	}
	return sql.NullBool{ Bool: *v, Valid: true }
}

func NullToBoolType(n sql.NullBool) bool {
	return n.Bool
}

func NullToBoolTypePtr(n sql.NullBool) *bool {
	if !n.Valid {
		return nil
	}
	return &n.Bool
}

/* -------------------- Int64Type -------------------- */

func Int64TypeToNull(v int64) sql.NullInt64 {
	return sql.NullInt64{ Int64: v, Valid: true }
}

func Int64TypePtrToNull(v *int64) sql.NullInt64 {
	if v == nil {
		return sql.NullInt64{}
	}
	return sql.NullInt64{ Int64: *v, Valid: true }
}

func NullToInt64Type(n sql.NullInt64) int64 {
	return n.Int64
}

func NullToInt64TypePtr(n sql.NullInt64) *int64 {
	if !n.Valid {
		return nil
	}
	return &n.Int64
}

/* -------------------- StringType -------------------- */

func StringTypeToNull(v string) sql.NullString {
	return sql.NullString{ String: v, Valid: true }
}

func StringTypePtrToNull(v *string) sql.NullString {
	if v == nil {
		return sql.NullString{}
	}
	return sql.NullString{ String: *v, Valid: true }
}

func NullToStringType(n sql.NullString) string {
	return n.String
}

func NullToStringTypePtr(n sql.NullString) *string {
	if !n.Valid {
		return nil
	}
	return &n.String
}

/* -------------------- TimeType -------------------- */

func TimeTypeToNull(v time.Time) sql.NullTime {
	return sql.NullTime{ Time: v, Valid: true }
}

func TimeTypePtrToNull(v *time.Time) sql.NullTime {
	if v == nil {
		return sql.NullTime{}
	}
	return sql.NullTime{ Time: *v, Valid: true }
}

func NullToTimeType(n sql.NullTime) time.Time {
	return n.Time
}

func NullToTimeTypePtr(n sql.NullTime) *time.Time {
	if !n.Valid {
		return nil
	}
	return &n.Time
}

/* -------------------- UUIDType -------------------- */

func UUIDTypeToNull(v uuid.UUID) uuid.NullUUID {
	return uuid.NullUUID{ UUID: v, Valid: true }
}

func UUIDTypePtrToNull(v *uuid.UUID) uuid.NullUUID {
	if v == nil {
		return uuid.NullUUID{}
	}
	return uuid.NullUUID{ UUID: *v, Valid: true }
}

func NullToUUIDType(n uuid.NullUUID) uuid.UUID {
	return n.UUID
}

func NullToUUIDTypePtr(n uuid.NullUUID) *uuid.UUID {
	if !n.Valid {
		return nil
	}
	return &n.UUID
}

